// Data — a small but realistic dataset
window.DATA = {
  brand: { name: "Skirts & Sparkles" },
  events: [
    {
      id: "ss-main",
      title: "Skirts & Sparkles",
      subtitle: "the main Saturday",
      date: { d: "24", m: "MAY", y: "2026", full: "Sat 24 May" },
      time: "22:00 – 06:00",
      venue: "NDSM werf, Amsterdam-Noord",
      venueShort: "NDSM · Amsterdam",
      travelFromCentraal: "12 min · free ferry",
      genres: ["techno", "house", "hybrid"],
      firstTimerFriendly: true,
      soldOut: false,
      priceFrom: 58,
      ticketsLeft: 84,
      resaleCount: 12,
      face: 65,
      cap: 71.50,
      tags: ["first-timer OK", "8 artists", "3 stages"],
      note: "A long, warm Saturday on the IJ. Good air, better speakers. Never been to one? This is a nice first one.",
      lineup: [
        { time: "22:00", name: "Sofia Kourtesis", room: "Main", kind: "opening", hero: false, gloss: null },
        { time: "23:30", name: "KI/KI", room: "Main", kind: "peak", hero: false, gloss: null },
        { time: "00:30", name: "Helena Hauff b2b Marcel Dettmann", room: "Main", kind: "peak", hero: true, gloss: "b2b = back-to-back: two DJs share a booth, swapping tracks every few minutes. Makes for high-energy, conversational sets." },
        { time: "02:30", name: "DJ Gigola", room: "Dome", kind: "late", hero: false, gloss: null },
        { time: "04:00", name: "Objekt (live)", room: "Main", kind: "closing", hero: true, gloss: "A live electronic set — not DJing other people's records, but performing their own music with hardware." },
        { time: "05:00", name: "Nala Sinephro", room: "Garden", kind: "closing", hero: false, gloss: null },
      ],
    },
    {
      id: "adams-warehouse",
      title: "Adam's Warehouse",
      subtitle: "the closing party",
      date: { d: "31", m: "MAY", y: "2026", full: "Sat 31 May" },
      time: "23:00 – 08:00",
      venue: "Warehouse Elementenstraat",
      venueShort: "Westpoort · Amsterdam",
      genres: ["hard techno", "hard groove"],
      firstTimerFriendly: false,
      soldOut: true,
      priceFrom: null,
      ticketsLeft: 0,
      resaleCount: 34,
      face: 65,
      cap: 71.50,
      resaleAvg: 64,
      tags: ["sold out", "harder techno", "long one"],
      note: "Harder, longer, later. Not for your first night out.",
      alertsSet: 2410,
      reappearRate: 0.72,
    },
    {
      id: "de-school-b2b",
      title: "De School · b2b night",
      subtitle: "hybrid live + DJ sets",
      date: { d: "07", m: "JUN", y: "2026", full: "Sat 7 Jun" },
      time: "23:00 – 06:00",
      venue: "De School",
      venueShort: "De Baarsjes · Amsterdam",
      genres: ["hybrid live", "techno"],
      firstTimerFriendly: true,
      soldOut: false,
      priceFrom: 42,
      ticketsLeft: 230,
      resaleCount: 5,
      face: 45,
      cap: 49.50,
      tags: ["hybrid live", "4 stages"],
      note: "Small and fast. Our editor's pick for week two.",
    },
    {
      id: "bij-het-ij",
      title: "BIJ het IJ · opening",
      subtitle: "sunset → late",
      date: { d: "22", m: "MAY", y: "2026", full: "Fri 22 May" },
      time: "19:00 – 02:00",
      venue: "IJ-haven terras",
      venueShort: "Overhoeks · Amsterdam",
      genres: ["melodic", "house"],
      firstTimerFriendly: true,
      soldOut: false,
      priceFrom: 28,
      ticketsLeft: 410,
      resaleCount: 0,
      face: 28,
      cap: 30.80,
      tags: ["outdoor", "early start"],
      note: "Outdoor. Sunset over the IJ. Melodic end of the spectrum.",
    },
  ],

  listings: [ // resale listings for Adam's Warehouse (sold-out)
    {
      id: "l1",
      seller: { name: "Lotte", sales: 23, verified: ["phone", "email", "instagram"], joined: "2022" },
      price: 64,
      face: 65,
      cap: 71.50,
      note: "Got stuck with a work trip — bought day one. English or NL both fine. x",
      listedAgo: "2h ago",
    },
    {
      id: "l2",
      seller: { name: "Yasin", sales: 8, verified: ["phone", "email"], joined: "2024" },
      price: 65,
      face: 65,
      cap: 71.50,
      note: null,
      listedAgo: "14m ago",
    },
    {
      id: "l3",
      seller: { name: "Marieke + Jonas", sales: 41, verified: ["phone", "email", "instagram"], joined: "2021" },
      price: 71,
      face: 65,
      cap: 71.50,
      note: "Two together. Won't split. Friend couple had to cancel last minute — it happens.",
      listedAgo: "5h ago",
      qty: 2,
    },
  ],

  glossary: {
    "b2b": "Back-to-back: two DJs share the booth, swapping tracks every few minutes.",
    "boiler room": "An intimate, crowd-surrounded set, often filmed. Origin: a London series.",
    "hybrid set": "A mix of DJing and live hardware performance in the same set.",
    "closing set": "The final slot of the night. Often the longest, most emotional one.",
    "peak time": "Roughly 00:30 – 03:00. The loudest, most danceable stretch.",
  }
};
